### PR TITLE
fix: drop color rendering

### LINKED ISSUE #16: Drop color not working
CSS issue
> Drop color doesn't seem to work

_Originally posted by @bhajneet in https://github.com/ShabadOS/theme-tool/pull/1#issuecomment-623015497_

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
* Drop colors now get rendered as required in desktop. 
* Refactors to write CSS in a function that can be exported and use in multiple places. 
* Fixes reset to default

### Tests for unexpected behavior
Before: Dropdown colors were not working.
image

After: 
image

### Time spent on PR
2 hours

### Linked issues
Fix #16 

### Reviewers
@Harjot1Singh

### CODE REVIEW

File: src/lib/utils.js [hunk 1]
```diff
@@ -65,13 +65,39 @@ export const loadStorage = () => {
...
+ * @param {string} key CSS variable to update.
+ * @param {string} value new value.
+ */
+export const writeCss = ( key, value ) => {
+  // Drop colors require to be string https://github.com/ShabadOS/desktop/blob/fc01ec563178ad605e42c2274b030da366063a13/app/frontend/src/Overlay/themes/Example.template#L82
+  if ( key.includes( 'drop' ) ) {
+    const rgba = getColorObject( value )
+    if ( rgba === null ) writeCssToDom( key, value )
+    else writeCssToDom( key, `${rgba.r}, ${rgba.g}, ${rgba.b}` )
+  } else writeCssToDom( key, localStorage[key] )
```
Comment (harjot1singh) [inline src/lib/utils.js]: It took me a while to understand what `key.includes( 'drop' )` actually means. I would prefer this to be handled in a more explicit manner, through declaration as an additional parameter in `options`.

Logic can be made more readable. Consider using early returns to reduce level of nesting, and reduce the calls to `writeCssToDom`, which appears to be superfluous. 

```suggestion
  if ( key.includes( 'drop' ) ) {
    const rgba = getColorObject( value )
    writeCssToDom( key, rgba ? `${rgba.r}, ${rgba.g}, ${rgba.b}` : value )
    
    return
  }
  
  writeCssToDom( key, localStorage[key] )
```

File: src/lib/utils.js [hunk 2]
```diff
@@ -65,13 +65,39 @@ export const loadStorage = () => {
...
+/**
+ * Returns a object with RGBA.
+ * @param {string} value RGBA
+ * https://stackoverflow.com/a/11003212/11321732
+ */
+const getColorObject = value => {
+  if ( [ 'none', 'undefined', null ].includes( value ) ) return null
+  const rgba = value.match( /\d+/g )
+  const rgbaObject = { r: rgba[0], g: rgba[1], b: rgba[2], a: rgba[3] }
+  return rgbaObject
```
Comment (harjot1singh) [inline src/lib/utils.js]: Destructure and save lives.

```suggestion
  if ( [ 'none', 'undefined', null ].includes( value ) ) return null

  const [ r, g, b, a ] = value.match( /\d+/g )
  return { r, g, b, a }
```

File: src/components/editors/ExportEditor.js [hunk 3]
```diff
@@ -31,9 +31,8 @@ const ExportEditor = () => {
 
   const resetEditor = () => {
     window.localStorage.clear()
-    loadStorage()
-    loadCss()
     setSettings( false )
+    window.location.reload()
```
Comment (harjot1singh) [inline src/components/editors/ExportEditor.js:35]: I'm still a little iffy about this, but it's acceptable I suppose.

**Review by harjot1singh — CHANGES_REQUESTED** [review]

File: src/lib/utils.js (hunk 1 above)
Comment (saihaj) [reply src/lib/utils.js]: I can change 'drop' to something more exact like 'drop-color'

Comment (harjot1singh) [reply src/lib/utils.js]: It's more that I don't think the idea of doing this based on part of the property name is robust, it's the kind of thing that might bite you in the future inadvertently

Comment (saihaj) [reply src/lib/utils.js]: But the options are not always being passed down. In case of loading from local storage the css variable is used. I can make it more explicit by just making sure that only those two specific drop colors are changed. 

```
  if ( [ OPTIONS.primaryDropColor.storageKey, OPTIONS.secondaryDropColor.storageKey ].includes( key ) ) {
    const rgba = getColorObject( value )
    writeCssToDom( key, rgba ? `${rgba.r}, ${rgba.g}, ${rgba.b}` : value )
  } else writeCssToDom( key, localStorage[key] )
```

Comment (harjot1singh) [reply src/lib/utils.js]: Whitelisting is also ok.

Comment (harjot1singh) [reply src/lib/utils.js]: I'd still suggest early-return + scrapping the `else`, as above. Less compact and more readable.

File: src/lib/utils.js [hunk 4]
```diff
@@ -65,13 +65,37 @@ export const loadStorage = () => {
...
+ * Writes values for CSS to the DOM
+ * @param {string} key CSS variable to update.
+ * @param {string} value new value.
+ */
+export const writeCss = ( key, value ) => {
+  // Drop colors require to be string https://github.com/ShabadOS/desktop/blob/fc01ec563178ad605e42c2274b030da366063a13/app/frontend/src/Overlay/themes/Example.template#L82
+  if ( DROP_COLORS.includes( key ) ) {
+    const rgba = getColorObject( value )
+    writeCssToDom( key, rgba ? `${rgba.r}, ${rgba.g}, ${rgba.b}` : value )
+  } else writeCssToDom( key, localStorage[key] )
```
Comment (Harjot1Singh) [inline src/lib/utils.js:91]:
```suggestion
  if ( DROP_COLORS.includes( key ) ) {
    const rgba = getColorObject( value )
    writeCssToDom( key, rgba ? `${rgba.r}, ${rgba.g}, ${rgba.b}` : value )
    return
  }
  
  writeCssToDom( key, localStorage[key] )
```

**Review by harjot1singh — DISMISSED** [review]

**Review by harjot1singh — APPROVED** [review]

File: src/components/editors/ExportEditor.js (hunk 3 above)
Comment (saihaj) [reply src/components/editors/ExportEditor.js:35]: Can try using this https://www.npmjs.com/package/use-force-update
