### PR TITLE
Disable opacity for font colors

### LINKED ISSUE #26: Font opacity should be disabled
**Describe the bug**
Font colors/font drop colors should not allow for opacity. Larivaar assist and vishraams can have opacity as they should have an inherited opaque value from the font color.

**Expected behavior**
Same pop up for color choice, but no opacity slider (or at the least not allow slider to affect value)

**Screenshots**
image

**Linked Issues**

Required by #16

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Add `disableAlpha` prop type to turn off alpha for color picker

Alpha slider is not shown for the following options in "Text":
* Primary and Secondary 
  * Font Color
  * Larivaar Assist Color
  * Drop Color

**Before**
image

**After**
image

### Tests for unexpected behavior
Colors can be changed with no issues.

### Time spent on PR
15 minutes

### Linked issues
Fix #26 

### Reviewers
@Harjot1Singh @bhajneet

### CODE REVIEW

File: src/components/SettingComponent.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ Button.defaultProps = {
   className: null,
 }
 
-export const PopoverColorPicker = ( { name, value, icon, storageKey, onChange, ...props } ) => {
+export const PopoverColorPicker = ( { name, value, icon, storageKey, onChange, disableAlpha, ...props } ) => {
```
Comment (harjot1singh) [inline src/components/SettingComponent.js]: You don't actually need to specify the `disableAlpha` prop here if you're just passing it through as-is in L140, since `{...props}` will spread it for you.

**Review by harjot1singh — CHANGES_REQUESTED** [review]

**Review by harjot1singh — APPROVED** [review]
